
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.brunofernandes.app;

import java.text.DecimalFormat;
/**
 *
 * @author Bwendel
 */
public class CalcIMC extends javax.swing.JFrame {

    /**
     * Creates new form CalcIMC
     */
    public CalcIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        lblHeader = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        txtAlturaMetros = new javax.swing.JTextField();
        lblMetros = new javax.swing.JLabel();
        txtAlturaCentimetros = new javax.swing.JTextField();
        lblAlturaCentimetros = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblTxtResultado = new javax.swing.JLabel();
        txtImc = new javax.swing.JTextField();
        lblTxtIndicacao = new javax.swing.JLabel();
        lblTxtIndicacao1 = new javax.swing.JLabel();
        txtImcRecomendado = new javax.swing.JTextField();
        lblTextForm = new javax.swing.JLabel();
        lblSaibaMais = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHeader.setText("Índice de massa corporal - Peso Ideal:");
        lblHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblAltura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAltura.setText("Altura:");

        txtAlturaMetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaMetrosActionPerformed(evt);
            }
        });

        lblMetros.setText("m");

        txtAlturaCentimetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlturaCentimetrosActionPerformed(evt);
            }
        });

        lblAlturaCentimetros.setText("cm.");

        lblPeso.setText("Peso:");

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblTxtResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTxtResultado.setText("O seu índice de massa corporal é:");

        txtImc.setEditable(false);
        txtImc.setText("IMC");
        txtImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImcActionPerformed(evt);
            }
        });

        lblTxtIndicacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTxtIndicacao.setText("Segundo a OMS, o índice ideal é entre 18,5 e 25.");

        lblTxtIndicacao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTxtIndicacao1.setText("Sendo assim, para sua altura o peso ideal é entre:");

        txtImcRecomendado.setEditable(false);
        txtImcRecomendado.setText("Kg mín / Kg máx");
        txtImcRecomendado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImcRecomendadoActionPerformed(evt);
            }
        });

        lblTextForm.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTextForm.setText("Fórmula -> IMC = Peso em kg divido pela altura em metros ao quadrado");

        lblSaibaMais.setText("Saiba mais sobre o Índice de Massa Corporal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlturaMetros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMetros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlturaCentimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAlturaCentimetros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTxtResultado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCalcular))
                            .addComponent(txtImc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTxtIndicacao1)
                            .addComponent(lblTxtIndicacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTextForm)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblSaibaMais))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(txtImcRecomendado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAlturaMetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMetros)
                    .addComponent(txtAlturaCentimetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlturaCentimetros)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxtResultado)
                    .addComponent(txtImc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lblTxtIndicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTxtIndicacao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtImcRecomendado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTextForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaibaMais)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlturaMetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaMetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaMetrosActionPerformed

    private void txtAlturaCentimetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaCentimetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaCentimetrosActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        int alturaMetros = Integer.valueOf(txtAlturaMetros.getText());
        float alturaCentimetros = Float.valueOf(txtAlturaCentimetros.getText());
        alturaCentimetros = alturaCentimetros / 100;
        float peso = Float.valueOf(txtPeso.getText());
        float altura = alturaMetros + alturaCentimetros;
        
        
        if(txtAlturaMetros.getText() != null && txtAlturaMetros.getText() != "") {
            if(txtAlturaCentimetros.getText() != null && txtAlturaCentimetros.getText() != "") {
                if(txtPeso.getText() != null && txtPeso.getText() != "") {
                    DecimalFormat numberFormat = new DecimalFormat("#.00");
                    
                    String resultado = String.valueOf(numberFormat.format(peso / Math.pow(altura, 2)));
                    txtImc.setText(resultado);
                    
                    String recomendadoMin = String.valueOf(numberFormat.format(18.5 * Math.pow(altura, 2)));
                    String recomendadoMax = String.valueOf(numberFormat.format(25 * Math.pow(altura, 2)));
                    
                    String resultadoRecomendado = recomendadoMin + "Kg/" + recomendadoMax + "Kg";
                    txtImcRecomendado.setText(resultadoRecomendado);
                }
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImcActionPerformed

    private void txtImcRecomendadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImcRecomendadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImcRecomendadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private java.awt.Label label1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblAlturaCentimetros;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblMetros;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblSaibaMais;
    private javax.swing.JLabel lblTextForm;
    private javax.swing.JLabel lblTxtIndicacao;
    private javax.swing.JLabel lblTxtIndicacao1;
    private javax.swing.JLabel lblTxtResultado;
    private javax.swing.JTextField txtAlturaCentimetros;
    private javax.swing.JTextField txtAlturaMetros;
    private javax.swing.JTextField txtImc;
    private javax.swing.JTextField txtImcRecomendado;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
